pimcore_web_to_print:
    generalTool: chromium
    generalDocumentSaveMode: default
    pdfreactorProtocol: null
    pdfreactorServer: ''
    pdfreactorServerPort: ''
    pdfreactorBaseUrl: ''
    pdfreactorApiKey: ''
    pdfreactorLicence: ''
    pdfreactorEnableLenientHttpsMode: false
    pdfreactorEnableDebugMode: false
    gotenbergHostUrl: ''
    gotenbergSettings: ''
    chromiumHostUrl: 'http://nginx:80'
    chromiumSettings: ''
